Fix GQA api detection on PyTorch<2.5.
Revert the detection of "use_gqa" to before
https://github.com/PriorLabs/TabPFN/pull/330.
In this PR the detection was bypassed to enable support for multi-gpu
training, but this breaks TabPFN if Pytorch is older than 2.5.
I copied the previous implementation from
https://github.com/PriorLabs/TabPFN/blob/17961ba58d6d1c9ec86d0e692909ba306f76d935/src/tabpfn/model/multi_head_attention.py.

In a follow-up PR I will fix multi-gpu training again.

Testing: This isn't picked up by the CI because we don't yet have GPU
tests enabled.

Before fix  (torch 2.4.1):
$ python examples/tabpfn_for_multiclass_classification.py
TypeError: scaled_dot_product_attention() got an unexpected keyword
argument 'enable_gqa'

After fix (torch 2.4.1 and torch 2.7.1):
$ python examples/tabpfn_for_multiclass_classification.py
ROC AUC: 1.0
Accuracy 0.98

Inference speed on 2.7.1 is unaffected by the change.